[workspace]
resolver = "2"

members = [
    "barnett-smart-card-protocol",
    "babyjubjub", 
    "proof-essentials", 
    "texas-holdem", 
    "WebRTC-in-Rust/wasm_client",
    "WebRTC-in-Rust/signalling-server", 
    "WebRTC-in-Rust/shared-protocol",
    #"WebRTC-in-Rust/turn-server"
]
