[workspace]
resolver = "2"

members = [
    "barnett-smart-card-protocol",
    "zk-reshuffle", 
    "babyjubjub", 
    "proof-essentials", "texas-holdem", "p2p-connection4", "p2p-neon", "p2p-web-assembly", "webrtc_datachannel"]
